packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  drizzle-orm: ^0.44.2
  drizzle-zod: ^0.8.2

  eslint: ^9.28.0
  eslint-config-next: ^15.3.4
  next: ^15.3.4
  next-mdx-remote: ^5.0.0
  postcss: ^8.5.4
  prettier: ^3.5.3
  sharp: ^0.34.2
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  zod: ^3.25.49
  '@dagrejs/dagre': ^1.1.5
  '@react-email/components': ^0.1.0
  '@tailwindcss/typography': ^0.5.16
  '@tanstack/react-query': ^5.80.7
  '@t3-oss/env-nextjs': ^0.13.8
  '@trpc/client': ^11.4.2
  '@trpc/tanstack-react-query': ^11.4.2
  '@trpc/server': ^11.4.2
  '@typescript-eslint/eslint-plugin': ^8.34.1
  '@typescript-eslint/parser': ^8.34.1
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5
onlyBuiltDependencies:
  - esbuild
