import type { AppRouterKeys } from '@barely/lib/trpc/app.route';

export const APP_ENDPOINTS: AppRouterKeys[] = [
	'analyticsEndpoint',
	'auth',
	'bio',
	'campaign',
	'cartFunnel',
	'cartOrder',
	'emailAddress',
	'emailBroadcast',
	'emailDomain',
	'emailTemplate',
	'emailTemplateGroup',
	'fan',
	'fanGroup',
	'file',
	'flow',
	'fm',
	'formResponse',
	'genre',
	'invoice',
	'invoiceClient',
	'landingPage',
	'link',
	'mailchimp',
	'mixtape',
	'playlist',
	'playlistPitchReview',
	'playlistPlacement',
	'pressKit',
	'product',
	'providerAccount',
	'spotify',
	'stat',
	'stripeConnect',
	'track',
	'user',
	'vipSwap',
	'visitorSession',
	'webDomain',
	'workspace',
	'workspaceInvite',
	'workspaceStripe',
] as const;
