export const genreIds = [
	'Blues---Boogie Woogie',
	'Blues---Chicago Blues',
	'Blues---Country Blues',
	'Blues---Delta Blues',
	'Blues---Electric Blues',
	'Blues---Louisiana Blues',
	'Blues---Modern Electric Blues',
	'Blues---Piano Blues',
	'Blues---Rhythm & Blues',
	'Blues---Texas Blues',

	'Electronic---Abstract',
	'Electronic---Acid',
	'Electronic---Acid House',
	'Electronic---Acid Jazz',
	'Electronic---Ambient',
	'Electronic---Bassline',

	'Electronic---Bleep',
	'Electronic---Breakbeat',
	'Electronic---Breakcore',
	'Electronic---Breaks',
	'Electronic---Broken Beat',
	'Electronic---Chillwave',
	'Electronic---Chiptune',
	'Electronic---Dance-pop',
	'Electronic---Dark Ambient',
	'Electronic---Darkwave',
	'Electronic---Deep House',
	'Electronic---Deep Techno',
	'Electronic---Disco',

	'Electronic---Downtempo',
	'Electronic---Drone',
	'Electronic---Drum n Bass',
	'Electronic---Dub',
	'Electronic---Dub Techno',
	'Electronic---Dubstep',

	'Electronic---EBM',
	'Electronic---Electro',
	'Electronic---Electro House',
	'Electronic---Electroclash',
	'Electronic---Euro House',
	'Electronic---Euro-Disco',
	'Electronic---Eurobeat',
	'Electronic---Eurodance',
	'Electronic---Experimental',
	'Electronic---Freestyle',
	'Electronic---Future Jazz',

	'Electronic---Garage House',

	'Electronic---Glitch',

	'Electronic---Grime',
	'Electronic---Halftime',
	'Electronic---Hands Up',
	'Electronic---Happy Hardcore',
	'Electronic---Hard House',
	'Electronic---Hard Techno',
	'Electronic---Hard Trance',
	'Electronic---Hardcore',
	'Electronic---Hardstyle',

	'Electronic---Hip Hop',
	'Electronic---Hip-House',
	'Electronic---House',
	'Electronic---IDM',

	'Electronic---Industrial',

	'Electronic---Jungle',

	'Electronic---Minimal',

	'Electronic---Neofolk',
	'Electronic---New Age',
	'Electronic---New Wave',
	'Electronic---Progressive House',
	'Electronic---Progressive Trance',
	'Electronic---Psy-Trance',

	'Electronic---Synth-pop',
	'Electronic---Synthwave',
	'Electronic---Techno',
	'Electronic---Tribal',
	'Electronic---Trip Hop',
	'Electronic---Tropical House',
	'Electronic---Vaporwave',
	'Folk, World, & Country---Bluegrass',
	'Folk, World, & Country---Country',
	'Folk, World, & Country---Folk',
	'Folk, World, & Country---Gospel',
	'Folk, World, & Country---Honky Tonk',

	'Funk / Soul---Contemporary R&B',
	'Funk / Soul---Disco',
	'Funk / Soul---Funk',
	'Funk / Soul---Gospel',
	'Funk / Soul---Neo Soul',
	'Funk / Soul---Psychedelic',
	'Funk / Soul---Rhythm & Blues',
	'Funk / Soul---Soul',

	'Pop---Ballad',
	'Pop---Bubblegum',
	'Pop---City Pop',
	'Pop---Europop',
	'Pop---Indie Pop',
	'Pop---J-pop',
	'Pop---K-pop',
	'Pop---Light Music',
	'Pop---Parody',
	'Pop---Vocal',
	'Reggae---Calypso',
	'Reggae---Dancehall',
	'Reggae---Dub',
	'Reggae---Lovers Rock',
	'Reggae---Ragga',
	'Reggae---Reggae',
	'Reggae---Reggae-Pop',
	'Reggae---Rocksteady',
	'Reggae---Roots Reggae',
	'Reggae---Ska',
	'Reggae---Soca',
	'Rock---AOR',
	'Rock---Acid Rock',
	'Rock---Acoustic',
	'Rock---Alternative Rock',
	'Rock---Arena Rock',
	'Rock---Art Rock',
	'Rock---Avantgarde',
	'Rock---Blues Rock',
	'Rock---Brit Pop',
	'Rock---Classic Rock',
	'Rock---Coldwave',
	'Rock---Country Rock',
	'Rock---Crust',
	'Rock---Death Metal',
	'Rock---Doo Wop',
	'Rock---Dream Pop',
	'Rock---Emo',
	'Rock---Ethereal',
	'Rock---Experimental',
	'Rock---Folk Rock',
	'Rock---Garage Rock',
	'Rock---Glam',
	'Rock---Goth Rock',
	'Rock---Grunge',
	'Rock---Hard Rock',
	'Rock---Hardcore',
	'Rock---Heavy Metal',
	'Rock---Indie Rock',
	'Rock---Industrial',
	'Rock---Krautrock',
	'Rock---Lo-Fi',
	'Rock---Lounge',
	'Rock---Math Rock',
	'Rock---Metalcore',
	'Rock---Mod',
	'Rock---Neofolk',
	'Rock---New Wave',
	'Rock---Noise',
	'Rock---Noisecore',
	'Rock---Nu Metal',
	'Rock---Pop Punk',
	'Rock---Pop Rock',
	'Rock---Post Rock',
	'Rock---Post-Hardcore',
	'Rock---Post-Metal',
	'Rock---Post-Punk',
	'Rock---Power Metal',
	'Rock---Power Pop',
	'Rock---Prog Rock',
	'Rock---Progressive Metal',
	'Rock---Psychedelic Rock',
	'Rock---Psychobilly',
	'Rock---Pub Rock',
	'Rock---Punk',
	'Rock---Rock & Roll',
	'Rock---Rockabilly',
	'Rock---Shoegaze',
	'Rock---Ska',
	'Rock---Sludge Metal',
	'Rock---Soft Rock',
	'Rock---Southern Rock',
	'Rock---Space Rock',
	'Rock---Speed Metal',
	'Rock---Stoner Rock',
	'Rock---Surf',
	'Rock---Symphonic Rock',
	'Rock---Thrash',
	'Rock---Twist',
] as const;
export type GenreId = (typeof genreIds)[number];
