import { EyeDropperIcon, ShareIcon, SparklesIcon } from '@heroicons/react/24/solid';
import {
	AlertCircle,
	AlertTriangle,
	AlignCenter,
	AlignCenterHorizontal,
	AlignCenterVertical,
	AlignEndHorizontal,
	AlignEndVertical,
	AlignJustify,
	AlignLeft,
	AlignRight,
	ArrowLeft,
	ArrowRight,
	AtSign,
	Banknote,
	Bell,
	Bold,
	Bot,
	CalendarRange,
	Check,
	CheckSquare,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Clipboard,
	ClipboardCheck,
	Code,
	Code2,
	Coins,
	Copy,
	Copyleft,
	Copyright,
	CreditCard,
	Crop,
	Database,
	DollarSign,
	Download,
	Edit,
	ExternalLink,
	Facebook,
	File,
	FileAudio,
	FileText,
	FileVideo,
	Filter,
	Flame,
	FlaskConical,
	FlipHorizontal,
	FlipVertical,
	Focus,
	FormInput,
	Gamepad,
	Gauge,
	Github,
	Globe,
	GripVertical,
	Hammer,
	Hash,
	Headphones,
	Heart,
	HelpCircle,
	Image,
	Import,
	Infinity as InfinityIcon,
	Instagram,
	Joystick,
	Laptop,
	LineChart,
	Link as LinkIcon,
	ListMusic,
	Loader2,
	Magnet,
	Megaphone,
	MessageSquare,
	Moon,
	MoreHorizontal,
	MoreVertical,
	Mountain,
	Music,
	Palette,
	PartyPopper,
	Pause,
	Phone,
	PieChart,
	Pizza,
	Play,
	Plus,
	QrCode,
	Radio,
	RectangleHorizontal,
	RectangleVertical,
	Redo,
	RefreshCcw,
	Rocket,
	Save,
	Search,
	Settings,
	Sliders,
	Square,
	Star,
	StarHalf,
	StickyNote,
	Sun,
	Tablet,
	Tag,
	Tags,
	Target,
	ThumbsDown,
	ThumbsUp,
	Trash,
	Trello,
	Triangle,
	Tv,
	Twitter,
	User,
	UserPlus,
	Users,
	Verified,
	Video,
	VolumeX,
	Wand2,
	Watch,
	Wrench,
	X,
	Youtube,
	Zap,
	ZoomIn,
	ZoomOut,
	type Icon as LucideIcon,
} from 'lucide-react';
import { FaSpotify, FaTiktok, FaTwitch } from 'react-icons/fa';
// import { IoSparkles } from 'react-icons/io5';
import type { IconType as ReactIcon } from 'react-icons/lib';

const Icon = {
	add: Plus,
	alert: AlertCircle,
	alignCenterHorizontal: AlignCenterHorizontal,
	alignCenterVertical: AlignCenterVertical,
	alignCenter: AlignCenter,
	alignEndHorizontal: AlignEndHorizontal,
	alignEndVertical: AlignEndVertical,
	alignJustify: AlignJustify,
	alignLeft: AlignLeft,
	alightRight: AlignRight,
	arrowLeft: ArrowLeft,
	arrowRight: ArrowRight,
	at: AtSign,

	bell: Bell,
	billing: CreditCard,
	bold: Bold,
	bot: Bot,
	broadcast: Radio,

	calendar: CalendarRange,
	check: Check,
	checked: CheckSquare,
	chevronUp: ChevronUp,
	chevronDown: ChevronDown,
	chevronLeft: ChevronLeft,
	chevronRight: ChevronRight,
	copy: Copy,
	clipboard: Clipboard,
	clipboardCopied: ClipboardCheck,
	close: X,
	code: Code,
	codeClosed: Code2,
	coins: Coins,
	copyleft: Copyleft,
	copyright: Copyright,
	creditCard: CreditCard,
	crop: Crop,

	database: Database,
	dollar: DollarSign,
	dots: MoreHorizontal,
	download: Download,

	edit: Edit,
	ellipsis: MoreVertical,
	externalLink: ExternalLink,
	eyeDropper: EyeDropperIcon,

	file: File,
	fileAudio: FileAudio,
	fileVideo: FileVideo,
	filter: Filter,
	fingerprint: Verified,
	flame: Flame,
	flipHorizontal: FlipHorizontal,
	flipVertical: FlipVertical,
	focus: Focus,
	formInput: FormInput,

	gamepad: Gamepad,
	gauge: Gauge,
	globe: Globe,
	grip: GripVertical,

	hammer: Hammer,
	hash: Hash,
	headphones: Headphones,
	heart: Heart,
	help: HelpCircle,

	import: Import,
	infinity: InfinityIcon,

	joystick: Joystick,

	kanban: Trello,

	laptop: Laptop,
	link: LinkIcon,
	lineChart: LineChart,
	loader: Loader2,

	magic: SparklesIcon,
	magnet: Magnet,
	media: Image,
	megaphone: Megaphone,
	message: MessageSquare,
	money: Banknote,
	moon: Moon,
	mountain: Mountain,
	music: Music,
	mute: VolumeX,

	page: File,
	palette: Palette,
	party: PartyPopper,
	pause: Pause,
	phone: Phone,
	pieChart: PieChart,
	play: Play,
	pizza: Pizza,
	playlist: ListMusic,
	plus: Plus,
	post: FileText,

	qr: QrCode,

	radio: Radio,
	rectangleHorizontal: RectangleHorizontal,
	rectangleVertical: RectangleVertical,
	redo: Redo,
	refresh: RefreshCcw,

	rocket: Rocket,
	// rocket2: RocketLaunchIcon,

	save: Save,
	search: Search,
	settings: Settings,
	share: ShareIcon,
	sliders: Sliders,
	spark: Zap,
	spinner: Loader2,
	square: Square,
	star: Star,
	starHalf: StarHalf,
	stickyNote: StickyNote,
	sun: Sun,

	tablet: Tablet,
	tag: Tag,
	tags: Tags,
	target: Target,
	test: FlaskConical,
	thumbsUp: ThumbsUp,
	thumbsDown: ThumbsDown,
	trash: Trash,
	triangle: Triangle,
	tv: Tv,

	user: User,
	userPlus: UserPlus,
	users: Users,

	verified: Verified,
	video: Video,

	wand: Wand2,
	warning: AlertTriangle,
	watch: Watch,
	wrench: Wrench,

	x: X,

	zap: Zap,
	zoomIn: ZoomIn,
	zoomOut: ZoomOut,

	facebook: Facebook,
	gitHub: Github,
	instagram: Instagram,
	spotify: FaSpotify,
	tiktok: FaTiktok,
	twitter: Twitter,
	twitch: FaTwitch,
	youtube: Youtube,
};

type IconType = LucideIcon | ReactIcon;

export { Icon, type IconType };
