name: Pull request closed

env:
  PLANETSCALE_ORG_NAME: ${{ secrets.PLANETSCALE_ORG_NAME }}
  PLANETSCALE_DB_NAME: ${{ secrets.PLANETSCALE_DB_NAME }}
  PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
  PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  
  # turbo build
  
  # You can leverage Vercel Remote Caching with Turbo to speed up your builds
  # @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
  
  turbo-build:
    name: Turbo Build
    runs-on: ubuntu-latest 
    if: ${{ !github.event.delete || github.event.action == 'opened' || github.event.action == 'synchronize' }}
    env: 
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm 
        uses: pnpm /action-setup@v2.2.4        
        
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=${pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}    
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps (with cache)
        run: pnpm i && pnpm i -r

      - name: Build
        run: pnpm turbo build link type-check

      - name: Check workspaces
        run: pnpm manypkg check

  # merge the db dev branch schema into the main db branch
  
  merge-db:
    name: Merge Planetscale Dev Branch
    runs-on: ubuntu-latest
    steps:      
      - name: Merge db branch
        id: merge-db-branch  
        uses: barelylabs/planetscale-branch-action
        with:
          action: 'merge'          

  # if turbo-build and merge-db succeed, delete the db dev branch

  delete-db:
    name: Delete Planetscale Dev Branch
    runs-on: ubuntu-latest
    needs: [turbo-build, merge-db]
    steps:      
      - name: Delete db branch
        id: delete-db-branch  
        uses: barelylabs/planetscale-branch-action
        with: 
          action: 'delete'
