name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          model: 'claude-opus-4-20250514'

          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"

          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"

          # Optional: Allow Claude to run specific commands
          allowed_tools: |
            Bash(pnpm i)
            Bash(pnpm format:fix)
            Bash(pnpm typecheck)
            Bash(pnpm test)
            Bash(pnpm build)
            Bash(pnpm lint)

          # Optional: Add custom instructions for Claude to customize its behavior for your project
          custom_instructions: |
            New branches from issues should have the naming convention of {type}/{description}_{issue-number}. type can be {feature | fix | chore | refactor | test | docs | style | perf | ci | build | revert | hotfix | security }
            Follow-up work on the same issue should be done in the same branch (don't create a new branch for follow-up work).
            Always run 'pnpm i' to enable lint, typecheck, and format:fix.
            Always run 'pnpm typecheck' to check for type errors and fix any errors.                        
            Always run 'pnpm lint' to run lint - fix any errors.
            Always run 'pnpm format:fix' before committing!

          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test
