name: Tinybird CI/CD

on:
  pull_request:
    paths:
      - 'external/tinybird/**'
      - '!external/tinybird/**.md'
      - '.github/workflows/tinybird-ci.yml'
  push:
    branches:
      - main
    paths:
      - 'external/tinybird/**'
      - '!external/tinybird/**.md'
      - '.github/workflows/tinybird-ci.yml'

jobs:
  validate:
    name: Validate Tinybird Resources in Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-tinybird-cli
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Tinybird CLI
        run: |
          pip install tinybird-cli
          tb --version

      - name: Authenticate Tinybird
        env:
          TB_TOKEN: ${{ secrets.TINYBIRD_API_KEY }}
        run: |
          cd external/tinybird
          tb auth --token $TB_TOKEN --no-interactive

      - name: Create or Use CI Branch
        if: github.event_name == 'pull_request'
        run: |
          cd external/tinybird
          BRANCH_NAME="ci_pr_${{ github.event.pull_request.number }}"

          # Try to use existing branch, create if it doesn't exist
          if ! tb branch use $BRANCH_NAME 2>/dev/null; then
            echo "Creating new branch: $BRANCH_NAME"
            tb branch create $BRANCH_NAME
            tb branch use $BRANCH_NAME
          else
            echo "Using existing branch: $BRANCH_NAME"
          fi

      - name: Push Changes to Branch
        if: github.event_name == 'pull_request'
        run: |
          cd external/tinybird
          echo "Pushing changes to CI branch..."
          tb push --force --no-interactive

          # Run diff to show what changed
          echo "\nChanges applied:"
          tb diff

      - name: Validate Main Branch (Push to main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd external/tinybird
          echo "Validating changes for main workspace..."
          tb push --dry-run --no-interactive

  deploy:
    name: Deploy to Main Workspace
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Tinybird CLI
        run: |
          pip install tinybird-cli
          tb --version

      - name: Authenticate Tinybird
        env:
          TB_TOKEN: ${{ secrets.TINYBIRD_API_KEY }}
        run: |
          cd external/tinybird
          tb auth --token $TB_TOKEN --no-interactive

      - name: Deploy to Main Workspace
        run: |
          cd external/tinybird
          echo "Ensuring we're on main workspace..."
          tb branch use main

          echo "Deploying changes to main workspace..."
          tb push --force --no-interactive

      - name: Verify Deployment
        run: |
          cd external/tinybird
          echo "Verifying deployment..."
          tb workspace current

          # Show recent changes
          echo "\nRecent changes:"
          tb diff

  cleanup:
    name: Cleanup CI Branches
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'closed' || github.event.action == 'merged')
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Tinybird CLI
        run: |
          pip install tinybird-cli

      - name: Authenticate Tinybird
        env:
          TB_TOKEN: ${{ secrets.TINYBIRD_API_KEY }}
        run: |
          tb auth --token $TB_TOKEN --no-interactive

      - name: Remove CI Branch
        run: |
          BRANCH_NAME="ci_pr_${{ github.event.pull_request.number }}"
          echo "Removing CI branch: $BRANCH_NAME"
          tb branch rm $BRANCH_NAME || echo "Branch already removed or doesn't exist"
